# Radiozoa configuration ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈

rros:
    i2c:
        id:                    1
        scl:                  38
        sda:                  18
        baud_rate:       400_000
    analog_control:
        pin:                   5       # analog 2 is 7
        deadband:              0.05
    motor_controller:
        pid:
            kp:                0.12
            ki:                0.03
            kd:                0.003
            kff:               0.80
        slew:
            vy:                0.05
            omega:             0.10
        closed_loop:        True
        pin_in1:               6       # port
        pin_in2:               4       # port
        pin_enc1A:            16       # port
        pin_enc1B:            17       # stbd
        pin_in3:              14       # stbd
        pin_in4:              12       # stbd
        pin_enc2A:             2       # stbd
        pin_enc2B:             1       # stbd
        pin_port_pix1:         5       # visualise pixel pins (set None to disable)
        pin_port_pix2:         7       # ditto
        pin_stbd_pix1:        17       # ditto
        pin_stbd_pix2:        19       # ditto
        period_ms:            50
    drive:
        enabled:            True
        startup_delay:         3       # in seconds
        pin_analog:           22
    roam:
        enabled:           False
        pin_analog:           22
    radiozoa:
        enabled:           False
        check_configured:   True
    devices:
      - index:                 0
        impl:          "VL53L1X"
        label:              "N0"       # red/grey
        address:            0x30
        pixel:                12
        xshut:                33
      - index:                 1
        impl:          "VL53L1X"
        label:             "NE1"       # red/white
        address:            0x31
        pixel:                15
        xshut:                 8
      - index:                 2
        impl:          "VL53L1X"
        label:              "E2"       # green/grey
        address:            0x32
        pixel:                18
        xshut:                10
      - index:                 3
        impl:          "VL53L1X"
        label:             "SE3"       # green/white
        address:            0x33
        pixel:                21
        xshut:                13
      - index:                 4
        impl:          "VL53L1X"
        label:              "S4"       # blue/grey
        address:            0x34
        pixel:                 0
        xshut:                15
      - index:                 5
        impl:          "VL53L1X"
        label:             "SW5"       # blue/white
        address:            0x35
        pixel:                 3
        xshut:                11
      - index:                 6
        impl:          "VL53L1X"
        label:              "W6"       # grey
        address:            0x36
        pixel:                 6
        xshut:                 9
      - index:                 7
        impl:          "VL53L1X"
        label:             "NW7"       # white
        address:            0x37
        pixel:                 9
        xshut:                34

#EOF
