# Radiozoa configuration ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈

rros:
    application:
        log_to_file:       False

    # behaviours ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
    drive:
        enabled:           False
        startup_delay:         3       # in seconds
        pin_analog:           22
    radiozoa:
        enabled:           False
        verbose:           False
        check_configured:   True
        force_configure:   False       # if True, force reconfiguration
    remote_control:
        enabled:            True
    roam:
        enabled:           False
        verbose:           False
        visualise:          True
        pin_analog:           22

    # components ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
    i2c:
        id:                    1
        scl:                  38
        sda:                  18
        baud_rate:       400_000
    analog_control:
        pin:                   5       # analog 2 is 7
        deadband:              0.05
    tof_publisher:
        verbose:           False
    eyeballs:
        enabled:            True
    ring:
        pin:                  21
        pixel_count:           8
        brightness:          0.1
    motor_controller:
        enabled:            True       # instantiated
        enabled_on_start:  False       # enabled when started
        verbose:           False
        visualise:          True
        closed_loop:        True
        pid:
            kp:                0.12
            ki:                0.000
            kd:                0.000
            kff:               0.80
        slew:
            vy:                0.05
            omega:             0.10
        power_scaler:        1.2       # scale power output to overcome weak vectors
        pin_in1:              14       # port
        pin_in2:              12       # port
        pin_enc1A:            16       # port
        pin_enc1B:            17       # stbd
        pin_in3:               6       # stbd
        pin_in4:               4       # stbd
        pin_enc2A:             2       # stbd
        pin_enc2B:             1       # stbd
        pin_port_pix1:         5       # visualise pixel pins (set None to disable)
        pin_port_pix2:         7       # ditto
        pin_stbd_pix1:        17       # ditto
        pin_stbd_pix2:        19       # ditto
        period_ms:            50

    # VL53 configuration ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
    devices:
      - index:                 0
        impl:          "VL53L1X"
        label:              "N0"       # red/grey
        address:            0x30
        pixel_24:             12
        pixel_8:               4
        xshut:                33
      - index:                 1
        impl:          "VL53L1X"
        label:             "NE1"       # red/white
        address:            0x31
        pixel_24:             15
        pixel_8:               5
        xshut:                 8
      - index:                 2
        impl:          "VL53L1X"
        label:              "E2"       # green/grey
        address:            0x32
        pixel_24:             18
        pixel_8:               6
        xshut:                10
      - index:                 3
        impl:          "VL53L1X"
        label:             "SE3"       # green/white
        address:            0x33
        pixel_24:             21
        pixel_8:               7
        xshut:                13
      - index:                 4
        impl:          "VL53L1X"
        label:              "S4"       # blue/grey
        address:            0x34
        pixel_24:              0
        pixel_8:               0
        xshut:                15
      - index:                 5
        impl:          "VL53L1X"
        label:             "SW5"       # blue/white
        address:            0x35
        pixel_24:              3
        pixel_8:               1
        xshut:                11
      - index:                 6
        impl:          "VL53L1X"
        label:              "W6"       # grey
        address:            0x36
        pixel_24:              6
        pixel_8:               2
        xshut:                 9
      - index:                 7
        impl:          "VL53L1X"
        label:             "NW7"       # white
        address:            0x37
        pixel_24:              9
        pixel_8:               3
        xshut:                34

#EOF
